name: Test
on: [push]
jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    container: swift:5.5-focal
    strategy:
      fail-fast: true
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        run: swift test
    